### ISSUE TITLE
Package signing key should be verified

### ISSUE THREAD

**Issue by nevart** [systemli/ansible-role-prosody#8]
The role ensures that the [key is present in the APT keystore which signs the package](https://github.com/systemli/ansible-role-prosody/blob/master/tasks/prosody.yml#L14).

However, no verification is done, which makes the initial installation (and/or upgrading) the package vulnerable to man-in-the-middle attacks.

Instead of fetching the key in an ad-hoc manner via the Internet, the key should probably either be stored in `files/`, or a checksum should be used to verify the downloaded key before adding it to the APT keystore.

Before doing this, it should be ensured, that the served key (or it's checksum) is sane and valid, via building some sort of trust path. Knowing the 40 char fingerprint of the key would help, for example.

**Comment by t2d** [comment]
Great idea! I added the checksum in https://github.com/systemli/ansible-role-prosody/commit/3986bcccd5b4ad0c7939a191cf95e52612fe9990
I'm just assuming I'm getting the same as everyone else (e.g. Travis CI). If you have a better idea, please send a PR..
