### ISSUE TITLE
Drop using apt-key, instead use signed-by option to limit the scope of the package signing key

### ISSUE THREAD

**Issue by nevart** [systemli/ansible-role-prosody#9]
The role [relies on `apt-key`](https://github.com/systemli/ansible-role-prosody/blob/master/tasks/prosody.yml#L14), to add the package signing to the global APT keystore.

However, this practice is deprecated since some time.

Instead of relying on the global APT keystore, the scope of the package signing key should be limited to the specific repository, the key is intended to sign packages of. This limits the ability of a rogue key to sign arbitrary packages served via a different repository.

That's possible since Debian stretch, via relying on to the `signed-by` option
documented in `sources.list(5)`. It's an option to

> require a repository to pass apt-secure(8) verification with a certain set of keys rather than all trusted keys apt has configured. It is specified as a list of absolute paths to keyring files (have to be accessible and readable for the _apt system user, so ensure everyone has read-permissions on the file) and fingerprints of keys to select from these keyrings. If no keyring files are specified the default is the trusted.gpg keyring and all keyrings in the trusted.gpg.d/ directory (see apt-key fingerprint). If no fingerprint is specified all keys in the keyrings are selected. A fingerprint will accept also all signatures by a subkey of this key, if this isn't desired an exclamation mark (!) can be appended to the fingerprint to disable this behaviour. The option defaults to the value of the option with the same name if set in the previously acquired Release file of this repository (only fingerprints can be specified there through). Otherwise all keys in the trusted keyrings are considered valid signers for this repository.

Making use of this could look like:

`sources.list.d/prosody.list`:
```
deb [signed-by=/usr/share/keyrings/prosody.gpg] https://packages.prosody.im/debian/ {{ ansible_distribution_release }} main
```

or, in Deb822 file format,

`sources.list.d/prosody.sources`:
```
Types: deb
URIs: https://packages.prosody.im/debian/
Suites: {{ ansible_distribution }}
Components: main
Signed-By: /usr/share/keyrings/prosody.gpg
```

The location used to stored the key is a proposal, following FHS, but probably something like `/usr/local/share/keyrings/prosody.gpg` might make sense as well, as this file is not installed by a Debian package.

Some final notes:

- Discussions are happening inside Debian to make this "the default", that is, to not ship anymore any globally trusted APT keys inside `/etc/apt/trusted.gpg.d`, but to instead ship individual keys in `/usr/share/keyrings/`. Obviously, the corresponding sources files would be shipped to make use of this.

- This allows, if used for third-party keys as well, to make it possible for a local administrator to run a tightly-administered system. Checks could be made for an empty `/etc/apt/trusted.gpg.d`, raising an alarm if any globally trusted APT key is installed there.

- Unfortunately, this didn't worked out yet for buster, but it looks quite good that this will be the default at least for bullseye, the release after buster.

- Doing it now, instead of in two years, could help pushing discussions and decisions, not only inside Debian, but also with "third-partys", via speaking to different upstreams and pushing for doc and practice changes.

- Pending your opinion, I'm happy to make the appropriate code changes, if this sounds valuable to you. Probably, this could go hand-in-hand with #8.

**Comment by t2d** [comment]
Good idea. Fixed by https://github.com/systemli/ansible-role-prosody/commit/3986bcccd5b4ad0c7939a191cf95e52612fe9990
